# ログレベルを指定します。
# 未指定でffmpegデフォルトのinfo
# 推奨 warning
loglevel: info

# 出力先フォルダを指定してください。
# <time>を含めることで、実行時間を埋め込んだ出力フォルダになります。
out_dir: out<time>\


# 使用するffmpegのパスを指定してください。
# システムパスに登録されたffmpegを使用する場合は'ffmpeg'と入力するか、空欄にしてください。
ffmpeg_path: ffmpeg

# 入力ファイルを指定してください。
input_file: input.mp4

# 試行するエンコーダーを指定してください。
# 現在はhevc_nvenc, hevc_qsvに対応しています。
encoder:
  - hevc_nvenc
  - hevc_qsv

# 試行するビットレートを指定してください。
# ビットレート指定エンコードを行わない場合は空欄にしてください。
bitrate:
  - 3000k
  - 5000k
  - 8000k

# 試行する品質を指定してください。
# 品質指定エンコードを行わない場合は空欄にしてください。
qp:
  - 18
  - 20
  - 22

# presetを指定します。
# 1(高速)～7(高画質)として、内部でエンコーダーに応じて自動設定されます。
# qsv   =  7, 6, 5, 4, 3, 2, 1
# nvenc = p1,p2,p3,p4,p5,p6,p7
preset:
  - 1
  - 4
  - 7

# look aheadを指定します。
look_ahead:
  - 0
  - 4

# GOP長を指定します。
gop:
  - 120

# 試行するプロファイルを指定してください。
profile:
  - main

